### ISSUE TITLE
 Showing Recent Messages Print: Entry, ":objects:=Array", Does Not Exist

### ISSUE THREAD

**Issue by a455455b** [HDB-Li/LLIconVersioning#1]
Hello,We have successfully integrated the script and applied it in CI.But I found some error messages.
I can get the correct path but the next thing may not match what the script wants.

Showing Error Messages:
ROOT_OBJECT is 56924D8B1A885ED20049D8FC
TARGET is 56924D921A885ED20049D8FC
BUILD_CONFIGURATION_LIST is 56924DB61A885ED20049D8FC
BUILD_CONFIGURATIONS is =Array {
    56924DB71A885ED20049D8FC
    56924DB81A885ED20049D8FC
}
Print: Entry, ":objects:=Array", Does Not Exist
Print: Entry, ":objects:{", Does Not Exist
ASSETCATALOG_COMPILER_APPICON_NAME=AppIcon-Debug
Print: Entry, ":objects:}", Does Not Exist

**Comment by a455455b** [comment]
咦!   @HDB-Li  原来是大佬你的库啊

**Comment by HDB-Li** [comment]
🤣  @a455455b   I know it , When I get an `Array` or `Dictionary` from `project.pbxproj`, `PlistBuddy` will return some extra content.

Such as if I want get `buildConfigurations` in `Dictionary`, Usually I think he's going to return an array which content is `[ "C4C640D92135831000FE6554","C4C640DA2135831000FE6554"]`, but in fact he returned an array like this `["=Array","{","C4C640D92135831000FE6554","C4C640DA2135831000FE6554","}"]`.
![1535968774612](https://user-images.githubusercontent.com/28746247/44980680-27f99c00-afa3-11e8-936f-faeea62f51a2.jpg)

** I guess I wrote the wrong shell language, but I don't know how to write it. Fortunately, it doesn't affect my use. **

**Comment by a455455b** [comment]
thks,It does not affect the results of the script.   I have a suggestion , you can change the command to execute the script:

chmod -R 777 $SRCROOT/LLIconVersioning.sh && $SRCROOT/LLIconVersioning.sh

Because script permissions issues may occur.

**Comment by HDB-Li** [comment]
I have already set chmod 777 in this file. It doesn't work?

**Comment by a455455b** [comment]
emmmm?  I didn't see it in the script description.

**Comment by HDB-Li** [comment]
I have set the file permissions to be `777`, and this setting property will remain in `LLIconVersioning.sh`, so I think you should not be using the `chmod -R 777` again.

**Comment by a455455b** [comment]
👌
