### ISSUE TITLE
中文文件夹会出现问题

### ISSUE THREAD

**Issue by swiftxy** [HDB-Li/LLIconVersioning#2]
刚好看到这个项目, 刚刚尝试了下.

我这边重新创建一个空的工程, 新建几个中文group, 再执行脚本后可能会出现乱码情况

**Comment by HDB-Li** [comment]
@JiaLiangoooo    I will try it today,  The group of Chinese name is in the image assets or in the project?

**Comment by swiftxy** [comment]
In the project. 

screenshots: 
![old](http://p1cek7azm.bkt.clouddn.com/993963D6-7B3A-4F15-BB25-B54D04C77897.png)
![new](http://p1cek7azm.bkt.clouddn.com/91635F30-A0F8-4FFE-8927-0219D299ED14.png)

**Comment by HDB-Li** [comment]
Thanks!!

**Comment by HDB-Li** [comment]
Hi @JiaLiangoooo  

I had try the real folder in `~/LLIconVersioningDemo/组件`, the folder create by `Right click - > New Group` and `Right click - > New Group With Folder`, but there's no messy code as your screenshots.  

I'm guessing that this might be influenced by the XCode version, right? Are you using XCode8 or XCode10.

![1537321125975](https://user-images.githubusercontent.com/28746247/45725941-d4688e80-bbef-11e8-9f87-e16bf3ebf939.jpg)

**Comment by swiftxy** [comment]
Sorry , I see it now.  My Xcode  is Version 10.0 (10A255).

**Comment by swiftxy** [comment]
It's not must reappear. I'm guessing that this may be my mistake.

when appear ![](http://p1cek7azm.bkt.clouddn.com/6B3AF83F-EAFA-408B-9466-4A38F63F8B27.png) .  -> Read From Disk will reappear it.
