### ISSUE TITLE
能够区分Release下的Ad Hoc证书吗

### ISSUE THREAD

**Issue by Shepkiswal** [HDB-Li/LLIconVersioning#3]
我的项目需要Ad Hoc证书打包后，也在Icon上添加版本信息，正式版不添加版本信息，请问目前的脚本支持这个操作吗？

**Comment by HDB-Li** [comment]
@Shepkiswal  Hi

Do you mean to use this script in **Release** or **other environments**? 

If you use the script only in *Release*, you can change the `Debug` to `Release` in line 27.

![1537320275664](https://user-images.githubusercontent.com/28746247/45725536-de898d80-bbed-11e8-893b-82fc3018852b.jpg)

If you use the script in all environments, Comment out 334 lines, 335 lines, and 347 lines.

![1537320701341](https://user-images.githubusercontent.com/28746247/45725752-d5e58700-bbee-11e8-8998-1db466ad5b33.jpg)

**Comment by Shepkiswal** [comment]
Thank you. This is very helpful to me！

**Comment by HDB-Li** [comment]
Ke Qi! 😆
